name: CI/CD Pipeline for Land-devops

on:
  pull_request:
    branches: [ main ] # Запускать при создании PR в ветку main
  push:
    branches: [ main ] # Запускать при пуше в ветку main (для сборки артефакта)

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Укажите вашу версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Замените на ваш файл зависимостей

    - name: Run quality checks
      run: |
        # Здесь можно добавить команды для запуска линтеров, статического анализа, тестов
        # Пример:
        # pylint your_bot_module
        # pytest

    - name: Build Docker image
      run: docker build . :${{ github.sha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push makarmarkov/land_devops:latest
        docker push makarmarkov/land_devops:${{ github.sha }}

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      run: |
        # Здесь можно добавить команды для развертывания Docker-образа
        # Например, обновление сервиса на сервере, запуск нового контейнера и т.д.
        echo "Deploying version ${{ github.sha }}"

  notify_telegram:
    needs: [build_and_test, deploy] # Ждать завершения сборки и развертывания
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          *CI/CD Notification*
          Project: Land-devops
          Status: ${{ job.status }}
          Commit SHA: ${{ github.sha }}
          Actor: ${{ github.actor }}
          Repository: ${{ github.repository }}
          Docker Image: makarmarkov/land_devops:${{ github.sha }}

          Full URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
